"""empty message

Revision ID: 13c47062f8b5
Revises: 
Create Date: 2019-04-23 14:30:59.021719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c47062f8b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uemail', sa.String(length=40), nullable=True))
    op.drop_index('uname', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uname', 'user', ['uname'], unique=True)
    op.drop_column('user', 'uemail')
    # ### end Alembic commands ###
